import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/'); await page.evaluate(() => localStorage.clear()); await page.reload() })

test('Local Demo 首页、动态 Day、地点攻略和直接路由正常', async ({ page }) => {
  await expect(page).toHaveTitle('GreenNote Travel')
  await expect(page.getByRole('link', { name: 'GreenNote Travel 首页' })).toContainText('GreenNote Travel')
  await expect(page.locator('.release-badge')).toHaveText('V1.0 · Demo')
  await expect(page.getByRole('heading', { name: '示例山海自驾 · 3 Days', level: 1 })).toBeVisible()
  await expect(page.locator('.day-card')).toHaveCount(3)
  await expect(page.getByRole('list', { name: '总路线' }).getByRole('listitem')).toHaveCount(4)
  await page.goto('/day/demo-day-1')
  await expect(page.getByRole('heading', { name: '青屿城 → 海湾步道 → 山居民宿' })).toBeVisible()
  await expect(page.getByRole('img', { name: '几何图形绘制的虚构海湾与步道' })).toBeVisible()
  await page.getByRole('link', { name: '查看完整攻略' }).click()
  await expect(page).toHaveURL(/\/place\/demo-baywalk$/)
  await expect(page.getByRole('heading', { name: '海湾步道', level: 1 })).toBeVisible()
  await expect(page.getByRole('heading', { name: '弹性安排' })).toBeVisible()
  await page.goto('/does-not-exist')
  await expect(page.getByRole('heading', { name: '这里不在计划路线中' })).toBeVisible()
})

test('无图片 Day 使用纯代码视觉且页面仍完整', async ({ page }) => {
  await page.goto('/day/demo-day-3')
  await expect(page.getByRole('heading', { name: '湖畔晨游 → 返回青屿城' })).toBeVisible()
  await expect(page.locator('.detail-hero-image')).toHaveCount(0)
  await expect(page.getByText('无图片 Day 示例')).toBeVisible()
})

test('管理员 Local 模式完成保存、预览、发布和备份恢复', async ({ page }) => {
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: '旅行计划管理' })).toBeVisible()
  await page.getByLabel('旅行名称').fill('我的 Demo 草稿')
  await page.getByRole('button', { name: '保存草稿' }).click()
  await expect(page.getByText(/保存成功/)).toBeVisible()
  await page.getByRole('button', { name: '草稿预览' }).click()
  await expect(page.getByText('未发布草稿预览')).toBeVisible()
  await expect(page.getByRole('heading', { name: '我的 Demo 草稿', level: 1 })).toBeVisible()
  await page.getByRole('link', { name: '返回管理页' }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.getByText(/已发布/).last()).toBeVisible()
  await page.getByRole('button', { name: '备份', exact: true }).click()
  await expect(page.getByText(/修订版/).last()).toBeVisible()
  await expect(page.getByRole('button', { name: '恢复为新修订版' }).first()).toBeVisible()
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '我的 Demo 草稿', level: 1 })).toBeVisible()
})

test('320px 无横向溢出并可从 PWA 缓存离线打开公开版', async ({ page, context }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.evaluate(() => navigator.serviceWorker?.ready)
  await page.reload()
  await page.waitForFunction(() => Boolean(navigator.serviceWorker?.controller))
  await context.setOffline(true)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: '示例山海自驾 · 3 Days', level: 1 })).toBeVisible()
  await context.setOffline(false)
})
